### ISSUE TITLE
Possible float overflow when magic duration > 4096sec

### ISSUE THREAD

**Issue by freevatar** [igroglaz/srvmgr#1]
The bug is related to magic duration when corresponding skill is high enough.

When magic duration is supposed to be `more than 4096sec`, overflow occurs and counter starts from zero.

_Here is an example:_
1. Case 1
Astral: `192`
Magic shield duration: `3944sec`

2. Case 2 (Overflow)
Astral: `194`
Magic shield duration: `47.6sec`

**Comment by serg-bloim** [comment]
Issue and fix explained:
https://github.com/igroglaz/srvmgr/wiki/Spell-duration-overflow

**Comment by igroglaz** [comment]
https://github.com/igroglaz/srvmgr/commit/91bb5e244dac2836b5b96e39e37634396b8e8668
