### ISSUE TITLE
Auto cast fireball doesnt work on flying units ( bat for specific )

### ISSUE THREAD

**Issue by PaddyVu** [igroglaz/srvmgr#119]
When i attack on ground units, my hero auto use fireball, however when attack bat, my hero hit with staff only

**Comment by PaddyVu** [comment]
Cant fix

**Comment by igroglaz** [comment]
one day I hope we will be able to fix it

**Comment by igroglaz** [comment]
linked to https://github.com/igroglaz/srvmgr/issues/13
