### ISSUE TITLE
elven scrolls casted as common scrolls

### ISSUE THREAD

**Issue by igroglaz** [igroglaz/srvmgr#29]
sometime elven scroll of earth protection applied as it was common scrolls. the same to other scrolls. it's a very rare chance, but it happens sometimes.

**Comment by igroglaz** [comment]
this is the same issue as https://github.com/igroglaz/srvmgr/issues/28
we've met a lot of such behaivour at our tournament, eg https://youtu.be/ADM26TkGdJM?t=435 - common blizzard scroll worked as elven

**Comment by serg-bloim** [comment]
It only affects tournaments, not usual gameplay.

**Comment by igroglaz** [comment]
usual gameplay too, see 1st message:
"sometime elven scroll of earth protection applied as it was common scrolls" you could be turned into stone without proper anti-stone prot ;)

Also as I've linked previously issue №28 ... elven curse fails -> you die from 1-2 blows from 4-5 mob

**Comment by igroglaz** [comment]
intented, no need to fix
