### ISSUE TITLE
Negative mana value

### ISSUE THREAD

**Issue by klen312** [igroglaz/srvmgr#43]
Negative mana value when casting "Light" scrolls to counter attach "Darkness" spell of a dragon3. Map: In and out. Screenshot attached.
![NegativeMana](https://user-images.githubusercontent.com/59899259/72393109-e2d7a380-376c-11ea-961e-577aa6cc86be.png)

**Comment by igroglaz** [comment]
actually this bug is very serious as it also influenced by using scrolls with a mage. top priority

**Comment by igroglaz** [comment]
I suppose easiest fix it - to prevent mage from using scrolls

**Comment by igroglaz** [comment]
https://github.com/igroglaz/srvmgr/commit/fd8f4ac689d0e413b3fedd0f348ec14ec3573cd6
