### ISSUE TITLE
add mage dmg modificator in PvP

### ISSUE THREAD

**Issue by igroglaz** [igroglaz/srvmgr#58]
to make mage more viable in PvP: to add damage multiplicator for mage's spells which will work only on other players in PvP, but monsters will receive the same damage as it written in data.

ZZYZX said that it's possible to do @ OnDamage:

```
if (player1 && player2 && !*(uint32_t*)(player1+0x2C) && !*(uint32_t*)(player2+0x2C) &&
    (*(uint8_t*)(unit1+0x4C) & 4))
    damage *= 3;
```

**Comment by serg-bloim** [comment]
What is the relation between this user story and that one #19 
If we implement #19 , do we need this one?

P.S. I do not propose to start working on #19 or close/delete the current issue.
