### ISSUE TITLE
add server flag for random map order

### ISSUE THREAD

**Issue by igroglaz** [igroglaz/srvmgr#62]
as we will have new quest map concept (a lot of quest maps, like ~24; each one will have one item in the boss) it will be fun to be able to randomize order of their appearence; so players will be able to get certain equipment no matter of their timezone.

Our server restarts every 24 hours, so having 24 maps (each map for 1 hour) - we have full cycle once per day, till restart.

**Comment by serg-bloim** [comment]
Another idea is to make a poll at the end of map. Like I remember in CS. So in chat players can pick the next map.
It would be extremely relevant for family guys, when you have 2 hours max from 10pm to 12am after work, home kids, etc.

The proposed behavior is:
Some time before end of the map Server lists all possible maps. Players may respond in chat what next map they want. If they have consensus, there was no 2 different responses, then server changes map as they wished. If they did not agree on the next map, server will decide by itself(either next from list or randomly from all maps or randomly from the players' responses) 

Alternative approach: players may request next map any time. Let's say I log in, see the map I don't like, I type into chat:
```
>>>change_map turtle_beach
```
Other players may do the same. And after this map finishes, the server will pick one of the selected maps.

**Comment by igroglaz** [comment]
Players may abuse polls, so it's better to stay on randomization feature. After all it will happen only on quest maps.

**Comment by igroglaz** [comment]
https://github.com/igroglaz/srvmgr/commit/dba05ab33c39cff6ec896979a115557fee196553

**Comment by igroglaz** [comment]
done https://github.com/igroglaz/rom2utils/commit/e230aefb40db5505da720c4ad2754476309a4413
