### ISSUE TITLE
minimum speed (to fix slow spell)

### ISSUE THREAD

**Issue by igroglaz** [igroglaz/srvmgr#89]
elven slow scroll (100) makes troll paralyzed.

/rfe make threshold of speed which can not be reduced.. threshold could be 8 (as troll.1 got it)

**Comment by Goury** [comment]
I'd like to suggest to cap slow effectiveness at 50% of target's base speed

**Comment by igroglaz** [comment]
https://github.com/igroglaz/srvmgr/commit/7e490db252409fcbfc2ab80b3bbc559989ab4cf6
