### ISSUE TITLE
some items dissapear after upgrade from tavern quest

### ISSUE THREAD

**Issue by igroglaz** [igroglaz/srvmgr#9]
When player trying to upgrade vamp staff in tavern and it's 17-25 already - it gives message about 'cheating' and removes other random staff from inventory (not vamp); eg removed spray staff from our player

**Comment by igroglaz** [comment]
There is also was such problem with mage's gloves. He had quest with reward 2.5kk experience and his gloves was +2 spirit. He've choosen a reward to upgrade them to +3 spirit - and they dissapear.

**Comment by igroglaz** [comment]
The same problem with shields:
Crystal shield +7 (or 8) air prot dissapeared

**Comment by serg-bloim** [comment]
Is this behavior consistent? Does it reproduce every time under same circumstances?

**Comment by igroglaz** [comment]
Yep. If you try to upgrade items with top properties - it will simply dissapear
